# https://github.com/otti/Growatt_ShineWiFi-S
# https://github.com/WilbertVerhoeff/Growatt
# https://community.home-assistant.io/t/esphome-modbus-growatt-shinewifi-s/369171
# https://gist.github.com/theneweinstein/f077003e8344f4111a7a6b69c192fd9c
# https://github.com/esphome/esphome/blob/dev/esphome/components/growatt_solar/growatt_solar.cpp
# https://www.amosplanet.org/wp-content/uploads/2022/12/%E9%80%9A%E4%BF%A1%E5%8D%8F%E8%AE%AEMAX_Growatt-Inverter-Modbus-RTU-Protocol_II-V1_13_20190116-English.pdf

substitutions:
  devicename: growatt-inverter
  friendly_name:  Growatt Inverter
  
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growatt-Inverter"
    password: !secret fallback_hotspot_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

#output:
# Blue Led
  #- id: light_bl
  #  platform: gpio
  #  pin: 16
# Green Led
  #- id: light_gr
  #  platform: gpio
  #  pin: 0
# Red Led
  #- id: light_rd
  #  platform: gpio
  #  pin: 2

uart:
  id: mod_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200
  
modbus:
  id: modbus1
  uart_id: mod_bus
  
modbus_controller:
  - id: growatt
# the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10

web_server:
  port: 80

text_sensor:
  - platform: version
    hide_timestamp: true
    name: '${friendly_name} - ESPHome Version'
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} - IP Address'
      icon: mdi:wifi
    ssid:
      name: '${friendly_name} - Connected SSID'
      icon: mdi:wifi-strength-2

button:
  - platform: restart
    name: '${friendly_name} - Restart'

sensor:
    # WiFi signal
  - platform: wifi_signal
    name: "${friendly_name} - WiFi Signal"
    update_interval: 120s

  - platform: growatt_solar
    update_interval: 10s
    protocol_version: RTU2

    inverter_status:
      name: "Growatt Status Code"

    phase_a:
      voltage:
          name: "Growatt Voltage Phase A"
      current:
          name: "Growatt Current Phase A"
      active_power:
          name: "Growatt Power Phase A"
    phase_b:
      voltage:
          name: "Growatt Voltage Phase B"
      current:
          name: "Growatt Current Phase B"
      active_power:
          name: "Growatt Power Phase B"
    phase_c:
      voltage:
          name: "Growatt Voltage Phase C"
      current:
          name: "Growatt Current Phase C"
      active_power:
          name: "Growatt Power Phase C"

    pv1:
      voltage:
          name: "Growatt PV1 Voltage"
      current:
          name: "Growatt PV1 Current"
      active_power:
          name: "Growatt PV1 Active Power"

    pv2:
      voltage:
          name: "Growatt PV2 Voltage"
      current:
          name: "Growatt PV2 Current"
      active_power:
          name: "Growatt PV2 Active Power"

    active_power:
      name: "Growatt Grid Active Power"

    pv_active_power:
      name: "Growatt PV Active Power"

    frequency:
      name: "Growatt Frequency"

    energy_production_day:
      name: "Growatt Today's Generation"

    total_energy_production:
      name: "Growatt Total Energy Production"

    inverter_module_temp:
      name: "Growatt Inverter Module Temp"
        
number:
  - platform: modbus_controller
    id: growatt_max_output
    name: "Growatt Max Output Rate"
    register_type: holding
    address: 0x3
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    skip_updates: 10
